### ISSUE TITLE
Installed via npm and when running I get an error Cannot find module 'markdownlint-cli2-formatter-default'

### ISSUE THREAD

**Issue by lizduke** [DavidAnson/markdownlint-cli2#19]

**Comment by DavidAnson** [comment]
Could you provide some more information, please? I have a GitHub Action that does this every night and passes. Here's a link to the latest run: https://github.com/DavidAnson/Workflows/runs/2246049565?check_suite_focus=true

What are steps to reproduce the issue? On what OS and Node version? What is the contents of your `node_modules` directory?

**Comment by liliankasem** [comment]
I'm seeing a similar issue which broke our PR pipeline, but with `markdownlint-cli2-formatter-junit`.

`markdownlint-cli2-formatter-junit` seems to be working great with v0.0.15 of markdownlint-cli2, but stopped working when the upgrade to v0.1.0 happened. 

What our pipeline is doing:

```
sudo npm i -g markdownlint-cli2
sudo npm i -g markdownlint-cli2-formatter-junit
markdownlint-cli2 "**/*.md"
```

Result using `markdownlint-cli2 v0.1.0 (markdownlint v0.23.1)`:

```
markdownlint-cli2 v0.1.0 (markdownlint v0.23.1)
Finding: **/*.md !**/venv
Linting: 13 file(s)
Summary: 0 error(s)
Error: Cannot find module 'markdownlint-cli2-formatter-junit'
Require stack:
- /usr/local/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at requireResolve (/usr/local/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:61:37)
    at /usr/local/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:69:36
    at Array.map (<anonymous>)
    at requireIds (/usr/local/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:69:24)
    at requireIdsAndParams (/usr/local/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:78:19)
    at outputSummary (/usr/local/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:531:11)
    at main (/usr/local/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:623:31)
    at async /usr/local/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:643:26 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js'
  ]
}
```

`test-markdownlint-results.xml` not generated.

Result using `markdownlint-cli2 v0.0.15 (markdownlint v0.23.1)`:

```
markdownlint-cli2 v0.0.15 (markdownlint v0.23.1)
Finding: **/*.md !**/venv
Linting: 13 file(s)
Summary: 0 error(s)
```

`test-markdownlint-results.xml` generated.

**Comment by DavidAnson** [comment]
@liliankasem Does this happen if you don’t install globally? That is a scenario I don’t (can’t) test in my own CI. I made a single change for 0.1.0 to work around a VS Code bug that may be relevant here.

**Comment by liliankasem** [comment]
In not installed globally it is not longer available as a global cli and fails `markdownlint-cli2: command not found` - should I be running the linter a different way if not globally installed?

**Comment by DavidAnson** [comment]
Okay, global is the scenario that broke. I'll release a patch in a moment.

Aside: I think it's unusual for a CI pipeline to install things globally, but it's not wrong. Within npm, you can run things from `node_modules` seamlessly. Here's an example of my nightly CI that installs all the formatters non-globally and works: https://github.com/DavidAnson/Workflows/blob/main/markdownlint-cli2/package.json

**Comment by DavidAnson** [comment]
Okay, I've updated the nightly tests to reproduce this problem (and verify the upcoming patch): https://github.com/DavidAnson/Workflows/actions/runs/710491308

I'm not sure I can test this within the project's CI, but will look into that later.

**Comment by DavidAnson** [comment]
@liliankasem @lizduke Please try version 0.1.1 newly published to npm which reverts to the previous `require` behavior that broke globally-installed scenarios. Thanks for the details, @liliankasem!

Proof: https://github.com/DavidAnson/Workflows/actions/runs/710529788

**Comment by liliankasem** [comment]
> Okay, global is the scenario that broke. I'll release a patch in a moment.
> 
> Aside: I think it's unusual for a CI pipeline to install things globally, but it's not wrong. Within npm, you can run things from `node_modules` seamlessly. Here's an example of my nightly CI that installs all the formatters non-globally and works: https://github.com/DavidAnson/Workflows/blob/main/markdownlint-cli2/package.json

Yeah totally agree, the funny thing is it's not a node project at all, but I guess it doesn't hurt to add a package.json just for pipelines sake.

Verified v0.1.1 is working for me - thanks for the quick fix and guidance!

**Comment by lizduke** [comment]
Yep works for me - thank you so much.

**Comment by DavidAnson** [comment]
I've updated the CI workflow that runs for every commit to validate the "install CLI2 and possibly formatters globally" scenario. Here's an example of it failing against v0.1.0: https://github.com/DavidAnson/markdownlint-cli2/runs/2258115885?check_suite_focus=true
